resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: registry.barrucadu.dev/rsync-resource
      username: registry
      password: ((docker-registry-password))

resources:
  - name: fonts-git
    type: git
    source:
      uri: git@github.com:barrucadu/fonts.git
      private_key: ((github-ssh-private-key))
  - name: cv-git
    type: git
    source:
      uri: https://github.com/barrucadu/cv.git
  - name: www-git
    type: git
    source:
      uri: https://github.com/barrucadu/barrucadu.co.uk.git
  - name: www-rsync--carcosa
    type: rsync-resource
    source:
      server: carcosa.barrucadu.co.uk
      remote_dir: /persist/srv/http/barrucadu.co.uk/www
      private_key: ((carcosa-ssh-private-key))
  - name: www-rsync--yuggoth
    type: rsync-resource
    source:
      server: yuggoth.barrucadu.co.uk
      remote_dir: /persist/srv/http/barrucadu.co.uk/www
      private_key: ((carcosa-ssh-private-key))

jobs:
  - name: update-pipeline
    plan:
      - get: www-git
        trigger: true
      - set_pipeline: www-barrucadu-co-uk
        file: www-git/concourse/pipeline.yml

  - name: build-and-deploy
    serial: true
    plan:
      - get: fonts-git
      - get: cv-git
        trigger: true
      - get: www-git
        trigger: true
      - task: build-site
        params:
          OUT_DIR: www
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: nixos/nix
          inputs:
            - name: www-git
          outputs:
            - name: site
          run:
            dir: www-git
            path: sh
            args:
              - -cex
              - |
                nix --extra-experimental-features "nix-command flakes" develop --command bash -c "./build --out=../site/${OUT_DIR}"
      - task: build-cv
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: texlive/texlive
          inputs:
            - name: fonts-git
              path: fonts
            - name: cv-git
            - name: site
          outputs:
            - name: site
          run:
            dir: cv-git
            path: sh
            args:
              - -cex
              - |
                latexmk -pdf -xelatex cv.tex
                mv cv.pdf ../site/www/cv.pdf
      - put: www-rsync--carcosa
        no_get: true
        params:
          path: site/www
          rsync_args:
            - --delete
      - put: www-rsync--yuggoth
        no_get: true
        params:
          path: site/www
          rsync_args:
            - --delete
